---
kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: tidy
    image: golang:1.19.2
    commands:
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
    depends_on: [clone]

  - name: lint
    image: golangci/golangci-lint:v1.50.1
    commands:
      - golangci-lint run -v -E gofmt
    depends_on: [clone]

  - name: vet
    image: golang:1.19.2
    commands:
      - go vet -race ./...
    depends_on: [clone]

  - name: build
    image: golang:1.19.2
    commands:
      - go build -race .
    depends_on: [clone]

  - name: gosec
    image: securego/gosec:2.14.0
    commands:
      - gosec -tests ./...
    depends_on: [clone]
---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - tag

steps:
  - name: test
    image: golang:1.19.2
    commands:
      - go test -v -race ./...
---
kind: signature
hmac: 826b09ef5bbd780a331af8595db2e1d0b6289f6e3c94ccc470a982fe6d01543e

...
